name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      matrix:
        rust: [stable, beta, nightly, 1.88.0, 1.82.0, 1.64.0, 1.57.0]

    steps:
    - uses: actions/checkout@v2
    - name: ci-1-88-version-env_vars
      if: ${{ matrix.rust == '1.88.0' }}
      run: echo "rustv=rust_1_88" >> $GITHUB_ENV

    - uses: actions/checkout@v2
    - name: ci-1-82-version-env_vars
      if: ${{ matrix.rust == '1.82.0' }}
      run: echo "rustv=rust_1_82" >> $GITHUB_ENV

    - uses: actions/checkout@v2
    - name: ci-1-64-version-env_vars
      if: ${{ matrix.rust == '1.64.0' }}
      run: echo "rustv=rust_1_64" >> $GITHUB_ENV

    - uses: actions/checkout@v2
    - name: ci-stable-or-later-env_vars
      if: ${{ matrix.rust == 'stable' || matrix.rust == 'beta' || matrix.rust == 'nightly' }}
      run: echo "rustv=rust_latest_stable" >> $GITHUB_ENV

    - name: ci-all-versions
      run: |
        rustup override set ${{ matrix.rust }}
        cargo update
          
        cd "${{github.workspace}}/const_panic_proc_macros/"
        cargo test

        cd "${{github.workspace}}/"
        cargo build --no-default-features
        cargo build
        cargo test --features "test"
        cargo test --no-default-features --features "test ${{env.rustv}}"
        cargo test --no-default-features --features "test ${{env.rustv}} non_basic"
        cargo test --no-default-features --features "test ${{env.rustv}} non_basic derive"

